import { useEffect, useState } from 'react'
import { Braces, Fingerprint, Play, RotateCcw } from 'lucide-react'
import { api } from '../services/api'
import { useAsyncAction } from '../hooks/useAsyncAction'
import type { EmbeddingResult, Scenario } from '../types'
import { CapabilityDetails } from '../components/CapabilityDetails'
import { FeatureVectorView } from '../components/FeatureVector'
import { PageHeading, Panel, Pill, SelectField } from '../components/Primitives'
import type { Notify } from './types'

export function CapabilitiesPage({ scenario, notify }: { scenario: Scenario; notify: Notify }) {
  const [selectedId, setSelectedId] = useState(scenario.capabilities[0]?.id ?? '')
  const [embedding, setEmbedding] = useState<EmbeddingResult | null>(null)
  const [stateId, setStateId] = useState(scenario.states[0]?.id ?? '')
  const [applicability, setApplicability] = useState<{ applicable: boolean; evidence: Array<{ predicate: Record<string, unknown>; satisfied: boolean }> } | null>(null)
  const { busy, run } = useAsyncAction((message) => notify(message, 'error'))
  const capability = scenario.capabilities.find((item) => item.id === selectedId)
  const state = scenario.states.find((item) => item.id === stateId)

  useEffect(() => { setSelectedId(scenario.capabilities[0]?.id ?? ''); setEmbedding(null); setStateId(scenario.states[0]?.id ?? ''); setApplicability(null) }, [scenario.id, scenario.capabilities, scenario.states])

  async function inspectEmbedding() {
    if (!capability) return
    const result = await run(() => api.encodeCapability(capability))
    if (!result) return
    setEmbedding(result)
    notify('Capability vector generated by the backend.', 'success')
  }

  async function checkState() {
    if (!capability || !state) return
    const result = await run(() => api.applicability(state, capability))
    if (result) setApplicability(result)
  }

  return <>
    <PageHeading eyebrow="EXPLORE / CAPABILITIES" title="Capability explorer" description="Inspect formal interfaces, state effects, constraints, mechanisms, and operational attributes." action={<Pill>{scenario.capabilities.length} capabilities</Pill>} />
    <Panel className="capability-selector-panel"><SelectField label="Capability" value={selectedId} onChange={(value) => { setSelectedId(value); setEmbedding(null); setApplicability(null) }}>
      {scenario.capabilities.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.type}</option>)}
    </SelectField>
      {capability && <div className="selected-meta"><span className="mono-id">{capability.id}</span><Pill tone="blue">{capability.type}</Pill><span className="mechanism-brief">{Object.entries(capability.mechanism).map(([key, value]) => `${key}: ${value}`).join(' · ') || 'No mechanism detail'}</span></div>}
    </Panel>

    {capability && <CapabilityDetails capability={capability} />}

    <div className="capability-lower-grid">
      <Panel><div className="panel-heading"><span className="panel-icon"><Braces size={17} /></span><div><h3>Embedding inspection</h3><p>Generate the problem-specific sparse vector through the API</p></div><button className="button button-primary push-right" onClick={inspectEmbedding} disabled={busy || !capability}>{busy ? <RotateCcw className="spin" size={15} /> : <Fingerprint size={15} />}Generate vector</button></div>
        {embedding ? <><div className="vector-summary"><strong>{embedding.dimension_count}</strong><span>active named dimensions</span><small>Dimensions are grouped by formal feature role.</small></div><FeatureVectorView vector={embedding.vector} /></> : <div className="empty-inline">Generate a vector to inspect the backend’s encoded dimensions.</div>}
      </Panel>
      <Panel><div className="panel-heading"><span className="panel-icon"><Play size={17} /></span><div><h3>State awareness</h3><p>Check preconditions and constraints against a formal state</p></div></div>
        <SelectField label="Evaluate against state" value={stateId} onChange={(value) => { setStateId(value); setApplicability(null) }}>
          {scenario.states.map((item) => <option value={item.id} key={item.id}>{item.id}</option>)}
        </SelectField>
        <button className="button button-secondary full-button" onClick={checkState} disabled={busy || !capability || !state}>Check applicability</button>
        {applicability && <div className="check-result"><div className="check-result-title"><span className={`result-indicator ${applicability.applicable ? 'pass' : 'fail'}`} />{applicability.applicable ? 'Applicable in this state' : 'Not applicable in this state'}</div>
          {applicability.evidence.map((row, index) => <div className="evidence-row" key={index}><code>{String(row.predicate.name)} {String(row.predicate.operator)} {JSON.stringify(row.predicate.value)}</code><Pill tone={row.satisfied ? 'green' : 'red'}>{row.satisfied ? 'satisfied' : 'missing / false'}</Pill></div>)}
          {!applicability.evidence.length && <p className="muted-note">No preconditions or constraints were declared.</p>}
        </div>}
      </Panel>
    </div>
  </>
}
